homeassistant: true

mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.22.10.191:1883
  user: homeassistant
  password: Polnocna17!

serial:
  port: tcp://172.22.10.88:6638
  adapter: zstack

frontend:
  port: 8080

advanced:
  network_key: GENERATE
  log_level: info

permit_join: false